### ISSUE TITLE
Alarm rings at wrong time when timeswitching

### ISSUE THREAD

**Issue by DSDV** [SimpleMobileTools/Simple-Clock#233] opened 2020-10-25 06:33 UTC
HI,

for example today the time switched from summertime to wintertime. Alarm was set to 8:30 and it startet at 7:30. Even showed 8:30. Phone clock was automaticly updated by android.

**Comment by grrrrr** [comment] 2020-10-25 09:55
Same issue here

- Alarm clock set to 09h00.   
- Clocks went back an hour on morning of 25th October and Android 10 correctly updated system time
- `Simple Clock`  rang the alarm at 08h00, an hour early
- Alarm settings screen shows alarm set for 09h00 but when alarm was ringing it showed 08h00 on ringing screen
- Additional to @DSDV  when 09h00 came around, `simple clock` rang again.

**Comment by Termuellinator** [comment] 2020-10-27 17:20
can confirm - i guess the clock is set via UTC and doesn't update the offset on time switch?

**Comment by grrrrr** [comment] 2020-10-27 17:44
To update my previous comment.

It will keep happening each day until you toggle the alarm entry off and on or delete the entry and create from scratch.

**Comment by DSDV** [comment] 2021-03-31 07:17
Still not fixed

workaround: dont use simple tools!

only app from them without mayor flaws is the gallery pro version from playstore (which is closed source and another dev team)....

**Comment by tibbi** [comment] 2021-11-08 16:50
duplicate of #151

**Closed by tibbi** 2021-11-08 16:50 UTC
