### ISSUE TITLE
[Feature] Save Timers

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Clock#273] opened 2021-05-07 16:05 UTC
requesting the ability to save timers.
for example if I want to save a 30 minute timer that I can click easily, everyday for a lunch break, I can do so without needing to set 30 min every time.

**Comment by tibbi** [comment] 2021-05-07 20:18
duplicate of #28

**Closed by tibbi** 2021-05-07 20:18 UTC
