### ISSUE TITLE
Back button CANCELS timer

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/Simple-Clock#173] opened 2020-03-01 19:31 UTC
When you set a timer, then press the phone's back button to resume your business, the timer is actually _cancelled_, without any notification. I don't think this is the desired behavior.

Simple Clock v5.0.4 on LineageOS 16 (Android 9).

**Comment by tibbi** [comment] 2020-03-01 20:39
duplicate of #77

**Closed by tibbi** 2020-03-01 20:39 UTC

**Comment by ltGuillaume** [comment] 2020-03-01 20:43
Is it? I don't see it, but perhaps it comes down to the same thing under the hood, then?

**Comment by tibbi** [comment] 2020-03-01 20:51
ye it is the same issue. The current implementation is a really primitive one. It stops once the app stops.

**Comment by ltGuillaume** [comment] 2020-03-01 20:54
Ah ok, that's a bit tricky then. Need to use a service for that?

**Comment by tibbi** [comment] 2020-03-01 21:00
maybe, not sure which solution is the best there. I always hated such background service-ish things.

**Comment by ltGuillaume** [comment] 2020-03-01 21:12
Me too, but afaik it's simpleL an activity can be thrown out any time by Android. Services don't have to be big things, but back when I dabbled with it, I found the broadcasting stuff a bit annoying.
