### ISSUE TITLE
timer stops when phone is turned of

### ISSUE THREAD

**Issue by Joppla** [SimpleMobileTools/Simple-Clock#169] opened 2020-02-24 22:05 UTC
Hi,

I use the timer usually for cooking, but when you turn off the screen the timer doesn't give an alarm. Only when the screen is on it works.

It this a bug or something with settings?

I use a Samsung S9 with Android 10

**Comment by tibbi** [comment] 2020-02-24 22:43
duplicate of #77

**Closed by tibbi** 2020-02-24 22:43 UTC
