### ISSUE TITLE
timer stops when locking phone

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Clock#57] opened 2018-05-21 20:25 UTC
Nokia6 on android 7.1.2   Simple Clock SC 4.0.0

Steps to reproduce:
Start a new timer of e.g. 10 minutes. leave the app open and counting. lock the phone. The timer will never alarm. 
If you check after eg 3mins the counter has only counted for 1min. It continous to count when unlocked and stops again after a while when locked.
i suspect battery management, already checked what i can.

Expected behavior:
Timer keeps counting down even when the phone is locked.

(actually same goes for the stopwatch)

**Comment by tibbi** [comment] 2020-02-24 09:52
duplicate of #77

**Closed by tibbi** 2020-02-24 09:52 UTC
Labels: bug
