### ISSUE TITLE
[Feature] Disable Alarm Temporarily 

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Clock#274] opened 2021-05-07 16:07 UTC
From what I can tell, there is no way to disable an alarm temporarily.
For example, if I have a daily alarm to wake me up at 5am, butbI wake up at 4am, that alarm will still go off at 5am. When I wake up at 4, it would be nice to be able to click disable alarm for today only, then tomorrow it rings again.
this makes it so I won't forget to enable the alarm later on, so it can still ring the next day, but can disable it today because I wake early.

**Comment by tibbi** [comment] 2021-05-07 20:17
duplicate of #265 indeed

**Closed by tibbi** 2021-05-07 20:17 UTC

**Comment by seniorm0ment** [comment] 2021-05-07 20:35
not exactly a duplicate, he requested for it to be a notification. I was requesting it in the app, although also +1ing his idea for the notification as well.
