### ISSUE TITLE
[Feature Request] Countdown presets

### ISSUE THREAD

**Issue by Ian2020** [SimpleMobileTools/Simple-Clock#276] opened 2021-05-22 11:32 UTC
I use the countdown a lot during the day for different things. It would be wonderful to be able to setup and choose from preset countdowns rather than have to change the clock every time. So maybe it would look something like this if you have saved more than one preset:

![PresetCountdowns](https://user-images.githubusercontent.com/7791246/119225013-3395a400-baf9-11eb-90d4-194255b505ca.png)

Then once you choose a countdown it just starts counting down and looks like it does now. You would need to be able to come out of a countdown and choose another though if you change your mind.

Thanks for this great app!

**Comment by tibbi** [comment] 2021-05-22 12:03
duplicate of #28

**Closed by tibbi** 2021-05-22 12:03 UTC

**Comment by Ian2020** [comment] 2021-05-22 12:22
Doh, sorry - I did search issues before I raised this but missed that one!
