### ISSUE TITLE
Timer 'Max reminder duration' does not work

### ISSUE THREAD

**Issue by ZarVladimirII** [SimpleMobileTools/Simple-Clock#198] opened 2020-04-28 10:12 UTC
The duration when the timer-alarm shuts himself off does not work anymore.
In 5.0.4 it did work within the range of this versions bug.
(The most superior function against stock clock)

**Comment by tibbi** [comment] 2022-07-03 14:51
duplicate of #296

**Closed by tibbi** 2022-07-03 14:51 UTC
