### ISSUE TITLE
continue countdown timer after closing the app

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Clock#39] opened 2018-04-05 21:14 UTC
Greetings and thank you for the great suite of apps.

Nokia 6 with Android 7.1.2.
When i start a countdown timer it only continues to count down when i keep the app open. Closing the app and re-opening it makes that the countdown timer is stopped and reset.

Expected behaviour: keep counting in the notification area even after the app is closed.

**Comment by tibbi** [comment] 2020-02-24 09:53
duplicate of #77

**Closed by tibbi** 2020-02-24 09:53 UTC
Labels: feature request
