### ISSUE TITLE
[Feature request] Add different timezones

### ISSUE THREAD

**Issue by GameHunter** [SimpleMobileTools/Simple-Clock#277] opened 2021-05-31 01:33 UTC
Hello.

Could you please add a possibility to have a clock widget with different time zone that the current one.
Is would be useful to know what is the time at homeland is I'm abroad.

Sincerely yours,
GH.

**Comment by tibbi** [comment] 2021-05-31 07:24
duplicate of #106

**Closed by tibbi** 2021-05-31 07:24 UTC
