### ISSUE TITLE
Feature Request: simple one time alarm (not tied to day of week)

### ISSUE THREAD

**Issue by djdalfaro** [SimpleMobileTools/Simple-Clock#38] opened 2018-04-05 02:30 UTC
One function I would appreciate is a simple alarm one time use feature. I would use this for my gym days where I have to wake up earlier than my normal days but its not always on the same day of week. As is, I have to set the day that my workout will be every week.

The way I see this working is this if the alarm was turned on without the day being set, the alarm would go off one time then switch to off. 

Example, Wednesday night knowing I have gym Thursday morning, I switch on the "gym" alarm which doesn't have a day set. It goes off Thursday morning and then switch itself off.

This functionality was in my previous clock app, but it is owned by "the company who shall not be named."

**Comment by ouzowtf** [comment] 2018-08-12 10:47
I miss this feature of non-day-tied alarms too and don't understand why this feature request was closed without an explanation.

**Comment by Solarunit** [comment] 2018-09-09 09:28
I miss this feature too. Looks like there is a duplicate here 
https://github.com/SimpleMobileTools/Simple-Clock/issues/58

**Comment by tibbi** [comment] 2020-03-07 22:03
duplicate of #58

**Closed by tibbi** 2020-03-07 22:03 UTC
