### ISSUE TITLE
Existing alarms do not follow dst change

### ISSUE THREAD

**Issue by aaron-grewell** [SimpleMobileTools/Simple-Clock#407] opened 2022-11-06 21:03 UTC
Our time changed today for dst, and I noticed that my existing 1pm alarm went off at noon. It displays the correct time but did not activate at the correct time. A newly created alarm went off at the correct time. Editing the existing alarm and changing the description seemed to cause it to recalculate which fixed the problem but not looking forward to doing this for all my alarms each time the time changes. Especially for wake up alarms this is problematic.

**Comment by tibbi** [comment] 2022-11-06 21:07
duplicate of #131

**Closed by tibbi** 2022-11-06 21:07 UTC
