### ISSUE TITLE
[Bug]Alarm Does Not Recognize Tome Setbacks

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Clock#309] opened 2021-11-09 08:18 UTC
Time was setback an hour 2 days ago, my next alarm was for today at 4am. Instead the alarm went off at 3am. But the clock on Android says it's 3am, and the clock on Simple Mobile shows it's 3am, so I'm unsure why it went off at 3am not 4am.
What doesn't make sense is it also went off again at 4am as it should have.

This is a major issue though, because it will mess up everyone's alarms but an hour

**Comment by tibbi** [comment] 2021-11-09 09:30
duplicate of #151

**Closed by tibbi** 2021-11-09 09:30 UTC
