### ISSUE TITLE
Alarms/Timer not working on Android 9 Pie

### ISSUE THREAD

**Issue by tomturbu** [SimpleMobileTools/Simple-Clock#125] opened 2019-01-11 10:28 UTC
Hi,

first of all, many thanks for these really great apps!

I have a Motorola One with Android Pie and SimpleClock. There seems to be an issue with alarms and also with timers, once the display gets locked, or the phone goes to sleep.

I've read a similar issue with the app clock+, and it seems that with Android 9 they changed a few things regarding running applications in the background.

I've already disabled battery optimization settings for SimpleClock.

How to reproduce?

Alarm:
Create an alarm for 5 minutes in the future, lock/sleep your phone, wait for the alarm to notify you, which will not happen.

Timer:
Create a timer for i.e. 1 minute, lock/sleep your phone, wait one minute, nothing will happen...

best regards!

**Comment by dietercastel** [comment] 2019-03-18 19:51
There seems to be similar bugs in other Alarm Clock apps e.g. https://github.com/philliphsu/ClockPlus/issues/53
It might be either an Android or Settings problem? Maybe try to whitelist the app in do not disturb mode?

**Comment by tibbi** [comment] 2019-03-18 21:37
there are so many system related things that can break reminders and alarms, that Im not even trying to get it right. Just check Google Clock reviews, how many people are complaining about it being unreliable at https://play.google.com/store/apps/details?id=com.google.android.deskclock&showAllReviews=true . If they cannot make it reliable, I cannot do it either.

**Comment by zoj613** [comment] 2019-05-01 06:18
I suggest adding clock to the unoptimized apps list. That fixed it for me.

**Comment by genodeftest** [comment] 2019-10-15 21:35
Probably a duplicate of #118.

**Comment by dietercastel** [comment] 2019-10-16 09:59
> I suggest adding clock to the unoptimized apps list. That fixed it for me.

You mean going to "Settings" -> "Battery Optimisation" -> "All Apps" -> "Clock" (with the orange icon) -> Change to "Not Optimised"?

I did that now, hope it helps. But haven't been missing alarms lately though.

Does someone know whether an app can request that permission from code in Android? That might be a useful (optional) addition I'd like to look into.

**Comment by zoj613** [comment] 2019-10-16 10:03
> > I suggest adding clock to the unoptimized apps list. That fixed it for me.
> 
> You mean going to "Settings" -> "Battery Optimisation" -> "All Apps" -> "Clock" (with the orange icon) -> Change to "Not Optimised"?
> 
> I did that now, hope it helps. But haven't been missing alarms lately though.
> 
> Does someone know whether an app can request that permission from code in Android? That might be a useful (optional) addition I'd like to look into.

yes. That option is supposed to protect the app from being dozed by the aggressive battery management of the system. I haven't had to do it at all now that im using a custom rom (AOSP and dotOS)

**Comment by anat0lius** [comment] 2020-02-18 21:49
On Android 10 too :(

**Comment by tibbi** [comment] 2022-04-24 15:43
Android 9 wont be supported anymore, retry again with 5.7.0

**Closed by tibbi** 2022-04-24 15:43 UTC
Labels: bug
