### ISSUE TITLE
time widget does not synchronize well

### ISSUE THREAD

**Issue by Joppla** [SimpleMobileTools/Simple-Clock#187] opened 2020-03-28 13:05 UTC
![Screenshot_20200328-140249_One UI Home](https://user-images.githubusercontent.com/25467829/77823658-ac1af380-70f4-11ea-80ff-88e59d6d0fab.jpg)

See screenshot. Left up the actual time, middle the widget.

**Comment by tibbi** [comment] 2020-03-28 15:28
duplicate of #62

**Closed by tibbi** 2020-03-28 15:28 UTC
