### ISSUE TITLE
[Feature Request] Create alarm without specified day of week

### ISSUE THREAD

**Issue by caminsha** [SimpleMobileTools/Simple-Clock#228] opened 2020-10-07 01:47 UTC
It would be great if there would be a feature that I can only set the time and the alarm will start the next time when this time will be reached.

> As a practical example (with 24h a day, not AM/PM)
> 
> Let's imagine it's 11:53.
> 
> I'd like to set an alarm at 13:15

So it would be great if it would be possible to create this alarm without defining a specific day of the week.

I think the #127 is a little bit related. 

I hope it's clear enough. Otherwise just ask.

**Comment by tibbi** [comment] 2020-10-07 06:53
so why reporting a duplicate of #127

**Closed by tibbi** 2020-10-07 06:53 UTC

**Comment by caminsha** [comment] 2020-10-07 07:29
> so why reporting a duplicate of #127

In my opinion it's not a duplicate.

 #127 Wants to have to have in alarm on a specific date in the future more like a calendar notification.

I asked for a feature that the alarm will be created for the next possible time.

**Comment by tibbi** [comment] 2020-10-07 08:14
it is the same
