### ISSUE TITLE
Clock: No sound for alarm while vibration-mode

### ISSUE THREAD

**Issue by Bikki4u** [SimpleMobileTools/Simple-Clock#434] opened 2023-02-13 22:19 UTC
I'm using the clock app for a while now, but not daily. Also when the phone is in vibration-mode.
A few weeks ago it appeared, when setting an alarm, 2 ringtones rang. It made no difference, when I set a different ringtone in the app. Always 2 ringtones at one time. (Maybe it was because the default ringtone in phone settings was different than the one I chose in the app for the alarm I set. This was my guess today.)
After changing the ringtone today, in vibration-mode there wouldn't come any sound for an "alarm" at all, just vibration. On the other hand when setting a "timer" in vibration-mode there is sound.
I deleted all alarms and tried again with ne alarms. No sound. I deinstalled the app, rebooted the phone, installed the app and tried again. Same issue. No ringtone sound in vibration-mode, just vibration.
When phone is in sound-mode, there is a ringtone sound for alarms.

I tried with another clock app (not simple mobile tools). It plays ringtone sound while vibration-mode.

Any chance to get a ringtone sound while vibration-mode (back)?

Phone: Fairphone4, Android 11 and Android 12
App Version: 5.10.0

Thanks

**Comment by beyond9thousand** [comment] 2023-07-05 04:04
Looks like this is a common problem with all users

**Comment by tibbi** [comment] 2023-07-05 08:08
duplicate of #453

**Closed by tibbi** 2023-07-05 08:08 UTC

**Comment by Bikki4u** [comment] 2023-11-23 18:01
I found out, in android 13 there was also no ringtone played. With a little help of the internet I found a solution that worked for me:
-> Change ringtone (the selected ringtone didn't exist anymore). 
Just for sure I deleted all alarms and set new ones.

Maybe that helps others
