### ISSUE TITLE
Issues with DST (Daylight Saving Time) Changes

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Clock#305] opened 2021-11-07 22:06 UTC
In the recent time change event, the Simple Clock rang two times. The first time was one hour earlier it should, and the other was on the right time. It looks like that Simple Clock has some issues with the DST changes.

**Comment by SkylerFur** [comment] 2021-11-08 04:49
I'll add that my alarm also rang an hour early, with the next alarm set to also an hour early. I opened each alarm ok-ed to save seems to have fixed it for me.

**Comment by tibbi** [comment] 2021-11-08 16:50
duplicate of #151

**Closed by tibbi** 2021-11-08 16:50 UTC
