### ISSUE TITLE
Alarm does not update on summer/winter time change

### ISSUE THREAD

**Issue by davidecalza** [SimpleMobileTools/Simple-Clock#151] opened 2019-11-01 11:23 UTC
On change from summertime to winter time, alarms have not been updated so they would trigger one hour before usual.

E.g. 
1) Alarm set at 07:00 AM
2) Summertime to wintertime change
3) Alarm changes to 06:00 AM

**Comment by J4gQBqqR** [comment] 2021-11-07 12:05
Oh, well, a feature request known for two years...
Thanks for the pointer.

**Comment by grrrrr** [comment] 2022-01-08 11:51
@tibbi could the label be changed to **bug**,  this should not be seen as a feature request as the hour change results in alarms ringing at the wrong time.

**Comment by tibbi** [comment] 2022-01-08 12:14
it doesnt matter what label is there... This app has been abandoned so it wont be fixed anytime soon.

**Comment by tibbi** [comment] 2022-04-24 15:43
duplicate of #131

**Closed by tibbi** 2022-04-24 15:43 UTC
Labels: feature request
