### ISSUE TITLE
[Feature Request] Add Default Alarm and Alarm Volume Changing Setting

### ISSUE THREAD

**Issue by ionuttbara** [SimpleMobileTools/Simple-Clock#538] opened 2023-10-09 21:09 UTC
A feature which you can change alarm volume and default alarm for all alarms  in settings.

**Comment by tibbi** [comment] 2023-10-09 21:12
volumes are handled by the system, not some app

**Comment by inson1** [comment] 2023-10-09 21:37
And default alarm is duplicate of #133

**Closed** 2023-10-09 21:44 UTC

**Comment by ionuttbara** [comment] 2023-10-10 11:10
> Member

but some apps such Google Clock and another F-Droid Project it have the ability to change alarm's volume in the app settings.
