### ISSUE TITLE
Home Time widget won't refresh after sleep.

### ISSUE THREAD

**Issue by ShadyGaDa** [SimpleMobileTools/Simple-Clock#113] opened 2018-11-12 12:31 UTC
I am using Launchtime on Samsung galaxy j5 with los 15.1

**Comment by tibbi** [comment] 2018-11-12 14:51
what sleep exactly you mean?

**Comment by ShadyGaDa** [comment] 2018-11-13 21:38
Sleep after 5 minutes of inactivity.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ShadyGaDa** [comment] 2018-11-21 07:19
This has become serious. Clock widget has to be constantly refreshed on wake up from home screen. It won't refresh after wake up.

**Comment by CarlFH** [comment] 2018-12-05 05:56
I can confirm a similar issue on Fairphone 2 with Android 6.0.1. The clock widget never get refresed, on that device. So is not usable, right now.

**Comment by bradleybee** [comment] 2019-04-23 17:38
I installed the clock yesterday and everything seemed to be going well but today my clock widget on my homescreen stopped refreshing as well.

If i open the clock app by tapping on the widget the app displays the correct time but the widget still doesn't refresh. 

If i resize the widget it will refresh the time or if i put another clock widget on the home screen the original widget will update.

I am using lawnchair launcher on a nexus 6p

**Comment by mobiustheory** [comment] 2020-02-10 19:34
I have the same issue.  The widget fails to automatically refresh when the screen is unlocked after timeout lock.  The widget only refreshes if I interact with it via touch to launch, touch-and-hold menu etc.

I can confirm the issue is repeatable if it's _after having been locked via screen timeout_ (5mins, in my case, as sounds like what has been reported by the OP ).  I have not seen the same thing happen if it is after the screen having been locked manually (almost always via the power button, in my case).

I am a new user on version 5.0.4, running stock Android 10 (build QQ1A.200205.002) and Nova Launcher 6.2.9.

**Comment by tibbi** [comment] 2020-03-28 15:28
duplicate of #62

**Closed by tibbi** 2020-03-28 15:28 UTC
