### ISSUE TITLE
time to wakeup call on day of summertime switch

### ISSUE THREAD

**Issue by dietmarczekay** [SimpleMobileTools/Simple-Clock#266] opened 2021-03-28 07:22 UTC
the calculation did not recognize the 1 hour shift for the night clocks set to summertime (and maybe the day back to normal time)

**Comment by BlizzardWizzard** [comment] 2021-11-01 05:05
> the calculation did not recognize the 1 hour shift for the night clocks set to summertime (and maybe the day back to normal time)

Yup, also doesn't work when it's set back to normal time... got woken up an hour early today.

**Comment by tibbi** [comment] 2022-04-24 15:44
duplicate of #131

**Closed by tibbi** 2022-04-24 15:44 UTC
Labels: bug
