### ISSUE TITLE
Feature Request: Analog Clock Widget

### ISSUE THREAD

**Issue by HardCode4All** [SimpleMobileTools/Simple-Clock#55] opened 2018-05-16 11:25 UTC
I really love your Tools and already bought them as well. Now I would love to use Simple Clock, but I don't like the digital clock widget. If you find the time, please create a "Simple Analog Clock Widget" which could look like this:

![screenshot_2018-05-16-13-16-48](https://user-images.githubusercontent.com/38424724/40114295-a40f5ca0-590c-11e8-9dbb-dd42eb10fbc6.png)

Just the simplest of analog clocks you could think of. Maybe with a configurable color. Oh and: touching the clock would open Simple Clock. Which is actually the reason why I cant't use Simple Clock at the moment: the widget you see here ( https://play.google.com/store/apps/details?id=net.ailuro.android.appwidget.clock ) opens the regular System Clock App and cannot be configured otherwise.

Thanks and keep up the good work. Simple Mobile Tools are just great!

**Comment by tibbi** [comment] 2018-05-16 12:18
it will eventually come, but this is a duplicate of #3

**Closed by tibbi** 2018-05-16 12:18 UTC

**Comment by HardCode4All** [comment] 2018-05-16 12:52
I see. Thanks.
