### ISSUE TITLE
Option to disable upcoming alarms within 5 minutes or so

### ISSUE THREAD

**Issue by randomguyrantaro** [SimpleMobileTools/Simple-Clock#462] opened 2023-06-16 19:58 UTC
sometimes I wake up before the alarm.

It would be handy, if the upcoming alarms could come as notifications so that users can disable them without opening up the app.

**Comment by tibbi** [comment] 2023-06-16 21:25
duplicate of #265

**Closed by tibbi** 2023-06-16 21:25 UTC
