### ISSUE TITLE
multiple timers

### ISSUE THREAD

**Issue by DoctorSubtilis** [SimpleMobileTools/Simple-Clock#268] opened 2021-04-09 11:24 UTC
Why you don't provide the possibility to set many timers (keeping them)? It is a feature present in other similar apps and it would be very useful if you reuse daily the same (several) timers. 
At least I would very appreciate this feature.
Thanks!

**Comment by tibbi** [comment] 2021-04-09 20:02
duplicate of #28

**Closed by tibbi** 2021-04-09 20:02 UTC
