### ISSUE TITLE
Bug found in Simple Clock.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [SimpleMobileTools/Simple-Clock#14] opened 2018-03-18 14:14 UTC
#### Expected behavior
On going to alarm section in clock then going to set the alarm after that I want to change the ringtone for alarm. 

#### Actual behavior
After clicking on ringtone option it brings me to the home screen. 

#### How to reproduce
Open the app. 

1:Go to alarm section by swiping right to left.
 
2:Open the alarm which you had kept. 

3:Press on default ringtone option. 

It will bring you to the home screen. 

* Browser: Simple Clock
* Version:3.1.1
* Operating system:5.1.1

#### Recording of bug
The recording of the bug is in this GIF. 
![20180318_184107.gif](https://steemitimages.com/DQmS9D9PqSgpxUwp2KL9DcXWKdJiepkPRfVWELA9vDPXY8c/20180318_184107.gif)  

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/bug-found-in-simple-clock">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Mirppc** [comment] 2018-03-20 18:35
i can confirm it works as intended without crashing on a Motorola G4 after testing this out.  i will test on another older device when i can.

version: 3.1.1
Operating System: 7.0

**Comment by 0xpr03** [comment] 2018-03-28 13:20
@Mirppc please just close it if you think it's too minor. The reporting account is 24 days old and posts only kind of abuse related issues to android repos (10+), all of them related to utopian, from which I've some response.

**Comment by tibbi** [comment] 2018-03-28 14:01
many reports from utopian are crap as they do it just for the reward, but this one actually makes sense

**Comment by Mirppc** [comment] 2018-03-28 17:44
@0xpr03 this isn't my post so no, i cannot close it.  from my experience some bugs can be sporadic like the steam #5030 bug.  This may be in fact a genuine issue but it may be related to hardware or android os or even something different.

**Comment by 0xpr03** [comment] 2018-03-28 20:35
guess I meant tibbi, didn't watch out for the "member" or "owner" badge

**Closed** 2018-03-29 08:57 UTC
Labels: bug
