### ISSUE TITLE
Simple Clock Widget

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-Clock#463] opened 2023-06-19 17:57 UTC
I would like a simple clock widget without the date. The date is too small anyways to see clearly; unless you plan on giving us an option to not include the date. Thanks

**Comment by Cryptophunk** [comment] 2023-06-23 17:26
duplicate of #267 from 2 years ago.

**Closed** 2023-06-23 20:03 UTC
Labels: feature request
