### ISSUE TITLE
Add Alarm Button (+) is Placed Directly on Top of A Toggle 

### ISSUE THREAD

**Issue by NoStepSnek** [SimpleMobileTools/Simple-Clock#194] opened 2020-04-22 11:19 UTC
Add alarm button is directly on top of the toggle of the bottom most alarm. Meaning that whichever alarm is last, will almost invariably be covered by the  (+) button. 

Work around:
In some instances, a sliver of the toggle peaks through and you can jusssst hit it. But in most cases instead of toggling the alarm, you instead launch the new alarm function. 

Whatever the last alarm is, just make two of them. That way when you scoll, the bottom alarm will still be impeded, but the duplicate will be in plain view just above it.

**Comment by tibbi** [comment] 2020-04-22 16:19
duplicate of #96

**Closed by tibbi** 2020-04-22 16:19 UTC
