### ISSUE TITLE
no alarm sound or alarm notification

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Clock#41] opened 2018-04-07 22:30 UTC
Nokia6 on Android 7.1.2.
Simple Clock (SC) version 3.1.2.

SC alarm used to work but since today no matter what alarm i program it does not work anymore.
- After creating an alarm a message is shown "the alarm will sound in xx minutes"
- The upcoming alarm time is correctly indicated in the notification area.
- When the time of the alarm is reached nothing happens. NO sound, NO notification in the notification area. The next alarm is now indicated in the notification area.
- What i have tried is to set alarms from 2min to 20mins ahead, for today or all days, with and without label, with different alarm sounds selected.
- Closing the app after setting an alarm or leaving it open at foreground or background does not matter.
- I cleared the SC app cache and settings, removed it, re-installed it but no change.
- The countdown timer works and produces sounds and the notification message.

Phone settings and volumes are checked, other apps produce sound, do-not-disturb is not enabled. SC alarm used to work but for now its back to use the stock clock app for alarms.

How can i further debug this?

**Comment by tibbi** [comment] 2018-04-08 07:09
not sure, but this is a duplicate of #24. Ill get there soon. Thanks

**Comment by GuitarBilly** [comment] 2018-04-12 18:12
Nokia6 on Android 7.1.2.
Simple Clock (SC) version 3.1.3.
Mine was not a duplicate of #24 as there it was reported that the notification of the alarm shows up. That is not the case on my phone. 

Also I see you closed this item but i still have no sound or notification when the alarm time is reached. However i found out something today.
STEP TO REPRODUCE MY PROBLEM : 
**1. create a new alarm. 
2. disable the alarm.
3. enable the alarm.**
now the alarm sounds and a notification is shown when the alarm is reached.

Without step 2 and 3 the app still displays "the alarm will ring in xx min" and the widget displays the alarm time of step 1 but NO alarm sound of notification is given.

**Comment by esmoak** [comment] 2018-05-17 11:45
Have the same issue on Moto G Play, Android 6.0.1.

I got one alarm to work and I believe it was because I inadvertently followed GuitarBilly's step above regarding creating, disabling, then enabling.

I'll see if I can troubleshoot in other ways.

**Comment by esmoak** [comment] 2018-05-17 11:45
Have the same issue on Moto G Play, Android 6.0.1.

I got one alarm to work and I believe it was because I inadvertently followed GuitarBilly's step above regarding creating, disabling, then enabling.

I'll see if I can troubleshoot in other ways.

**Comment by tibbi** [comment] 2018-05-17 11:51
retry with version 4.0.0, something related to the freshly created alarm scheduling has changed

**Comment by esmoak** [comment] 2018-05-17 11:55
@tibbi I'll try that, but for some reason 4.0.0 isn't showing as an update on F-Droid for me yet. A bunch of your other apps went to 4.0 or 4.0.3 last night, but clock didn't. Thanks.

**Comment by GuitarBilly** [comment] 2018-05-17 17:51
Thanks for this update/reminder, just tried with version 4.0.0.
For me all works now as expected, no workarounds needed.

**Comment by tibbi** [comment] 2018-05-17 18:27
okay, thanks. Ill close it then, reopen it if still broken.

**Closed by tibbi** 2018-05-17 18:27 UTC
Labels: bug
