### ISSUE TITLE
alarms: add button in the way to disable alarm

### ISSUE THREAD

**Issue by alexanderdd** [SimpleMobileTools/Simple-Clock#186] opened 2020-03-28 12:43 UTC
Thank you for this app!

The last alarm cannot be enabled/disabled because the floating add button is in the way.
![Screenshot_20200328-134006](https://user-images.githubusercontent.com/28591861/77823272-184c2600-70fa-11ea-8f4c-b3630afb7122.png)

**Comment by tibbi** [comment] 2020-03-28 15:27
duplicate of #96

**Closed by tibbi** 2020-03-28 15:27 UTC
