### ISSUE TITLE
Timer input without spinners

### ISSUE THREAD

**Issue by rerobins** [SimpleMobileTools/Simple-Clock#68] opened 2018-06-06 16:16 UTC
Please allow timer times to be inputted through keyboard entry instead of spinners.

**Comment by MartinGSch** [comment] 2018-08-20 08:04
I would also welcome this feature request. If you have any doubts about it, enter a time of 30 min... a pain with the spinners. In fact the spinners in the clock app that Sony delivers have been the trigger for me to start looking for an alternative app.

**Comment by bokf** [comment] 2018-10-08 11:02
I like the way to input the time from cyanogenmod pressing the digits. It is very fast and easy.


![screenshot_2018-10-08-11-30-58](https://user-images.githubusercontent.com/25562831/46605562-37b45500-cafa-11e8-9168-cfba7e64c184.png)

**Comment by ltGuillaume** [comment] 2020-03-01 18:58
Same here. Spinners are a real pain.

**Comment by alexanderdd** [comment] 2020-03-28 12:31
Anybody know a command/module/library that can be  implemented to allow keyboard input?

**Comment by tibbi** [comment] 2023-08-17 09:43
duplicate of #404

**Closed by tibbi** 2023-08-17 09:43 UTC
Labels: feature request
